import { Product } from "./types";

export const Products: Product[] = [ 
    { 
        id: 1,
        name: "Brushed Reglan Shirt",
        tagline:"Dress",
        category: "female",
        price: 205,
        image: "/productpic2.png", 
    }, 
    { 
        id: 2,
        name: "Cameryn Sash  Dress",
         tagline:"Dress",
        category: "female",
        price: 280,
        image: "/productpic2.png", 
    }, 
    { 
        id: 3,
        name: "Seamless Sweat Shirt",
         tagline:"Dress",
        category: "female",
        price: 205,
        image: "/productpic3.png", 
    }, 
    { 
        id: 4,
        name: "Flex Sweat Shirt",
         tagline:"Dress",
        category: "female",
        price: 205,
        image: "/productpic4.png", 
    }, 
    { 
        id: 5,
        name: "Pink Fleece pants",
         tagline:"Dress",
        category: "female",
        price: 205,
        image: "/productpic5.png", 
    }, 
    { 
        id: 6,
        name: "Lite Sweatpant",
         tagline:"Dress",
        category: "female",
        price: 205,
        image:"/productpic6.png", 
    }, 
    { 
        id: 7,
        name: "Imperial Alpaca Hoodie",
         tagline:"Dress",
        category: "kids",
        price: 205,
        image: "/productpic7.webp", 
    }, 
    { 
        id: 8,
        name: "Flex Push Button Bomber",
         tagline:"Dress",
        category: "male",
        price: 205,
        image: "/productpic8.png", 
    }, 
    { 
        id: 9,
        name: "Reglan Sweat Shirt",
         tagline:"Dress",
        category: "male",
        price: 205,
        image:"/productpic9.png", 
    }
];